# Generated by Django 5.0.6 on 2024-07-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.SlugField(max_length=70, verbose_name='Code on Book')),
                ('title', models.CharField(max_length=70, verbose_name='Book Title')),
                ('issued', models.DateField(verbose_name='Issued Date')),
                ('author', models.CharField(max_length=70, verbose_name='Authors Name')),
            ],
        ),
    ]
